---
- name: Create Zookeeper group
  group:
    name: "{{ OS_ZOOKEEPER_GROUP }}"
    state: present
    system: yes
  tags: install

- name: Create Zookeeper user
  user:
    name: "{{ OS_ZOOKEEPER_USER }}"
    group: "{{ OS_ZOOKEEPER_GROUP }}"
    state: present
    create_home: no
    system: yes
  tags: install

- name: Check if Zookeeper has already been downloaded and unpacked
  stat:
    path: "{{ ZOOKEEPER_HOME }}"
  register: zoo
  tags: ['start', 'stop', 'install', 'uninstall', 'info']

- name: Install Zookeeper
  include: install.yml
  when: not zoo.stat.exists
  tags: install

- name: Start Zookeeper
  systemd:
    daemon_reload: yes
    name: zookeeper
    state: started
    enabled: yes
  when: zoo.stat.exists
  tags: start

- name: Stop Zookeeeper
  systemd:
    daemon_reload: yes
    name: zookeeper
    state: stopped
    enabled: no
  when: zoo.stat.exists
  tags: ['stop', 'uninstall']

- name: Check Zookeeper service status
  shell: systemctl status zookeeper
  ignore_errors: yes
  tags: ['start', 'stop', 'uninstall', 'info']
  register: zoos_status

- debug: msg="{{ zoos_status.stdout }}"
  tags: ['start', 'stop', 'uninstall', 'info']

- name: Check Zookeeper status
  shell: "{{ ZOOKEEPER_STATUS_COMMAND }}"
  ignore_errors: yes
  tags: ['start', 'info']
  register: zoo_status

- debug: msg="{{ zoo_status.stdout }}"
  tags: ['start', 'info']

- name: Uninstall zookeeper
  include: uninstall.yml
  when: zoo.stat.exists
  tags: uninstall
