---
- name: Download Elasticsearch
  get_url:
    url: "{{ ELASTICSEARCH_URL }}"
    dest: "{{ INSTALLATION_DIR }}"
    mode: 0644

- name: Unpack Elasticsearch
  unarchive:
    src: "{{ INSTALLATION_DIR }}/{{ ELASTICSEARCH_TAR }}"
    dest: "{{ INSTALLATION_DIR }}"
    remote_src: yes
    mode: 0644
    list_files: yes
  register: archive_contents

- name: Create Elasticsearch home directory
  copy:
    src: "{{ INSTALLATION_DIR }}/{{ archive_contents.files[0].split('/')[0] }}/"
    dest: "{{ ELASTICSEARCH_HOME }}"
    remote_src: yes

- name: Set Elasticsearch directory permissions
  file:
    path: "{{ ELASTICSEARCH_HOME }}"
    state: directory
    group: "{{ ELASTICSEARCH_OS_GROUP }}"
    owner: "{{ ELASTICSEARCH_OS_USER }}"
    mode: 0755
    recurse: yes

- name: Remove Elasticsearch archive
  file:
    path: "{{ INSTALLATION_DIR }}/{{ ELASTICSEARCH_TAR }}"
    state: absent

- name: Remove unpacked directory
  file:
    path: "{{ INSTALLATION_DIR }}/{{ archive_contents.files[0].split('/')[0] }}/"
    state: absent

- name: Place Elasticsearch systemd service file to /etc/systemd/system
  template:
    src: elasticsearch.service.j2
    dest: /etc/systemd/system/elasticsearch.service
