---
- name: Download Kibana
  get_url:
    url: "{{ KIBANA_URL }}"
    dest: "{{ INSTALLATION_DIR }}"
    mode: 0644

- name: Unpack Kibana
  unarchive:
    src: "{{ INSTALLATION_DIR }}/{{ KIBANA_TAR }}"
    dest: "{{ INSTALLATION_DIR }}"
    remote_src: yes
    mode: 0644
    list_files: yes
  register: archive_contents

- name: Create Kibana home directory
  copy:
    src: "{{ INSTALLATION_DIR }}/{{ archive_contents.files[0].split('/')[0] }}/"
    dest: "{{ KIBANA_HOME }}"
    remote_src: yes

- name: Set Kibana directory permissions
  file:
    path: "{{ KIBANA_HOME }}"
    state: directory
    group: "{{ KIBANA_OS_GROUP }}"
    owner: "{{ KIBANA_OS_USER }}"
    mode: 0755
    recurse: yes

- name: Remove Kibana archive
  file:
    path: "{{ INSTALLATION_DIR }}/{{ KIBANA_TAR }}"
    state: absent

- name: Remove unpacked directory
  file:
    path: "{{ INSTALLATION_DIR }}/{{ archive_contents.files[0].split('/')[0] }}/"
    state: absent

- name: Place Kibana systemd service file to /etc/systemd/system
  template:
    src: kibana.service.j2
    dest: /etc/systemd/system/kibana.service
